### ISSUE TITLE
Add BALANCE_NOTIFICATIONS_EMAIL env variable

### ISSUE THREAD

**Issue by dOrgJelli** [dOrgTech/TxPayerService#25]
Add BALANCE_NOTIFICATIONS_EMAIL env variable, and send an email to it whenever the balance reaches below a certain threshold (could be an env variable as well).

**Comment by dOrgJelli** [comment]
@Flash-Git is this finished?

**Comment by Flash-Git** [comment]
Yep! I opened a pull request into dev [here](https://github.com/dOrgTech/TxPayerService/pull/40)
