### ISSUE TITLE
Turn Into Netlify Function W/ One-Click Deploy

### ISSUE THREAD

**Issue by dOrgJelli** [dOrgTech/TxPayerService#26]
Make the project deployable as a Netlify function and add a one-click deploy button to the README

**Comment by orishim** [comment]
I'll also contact them regarding a free open-source plan.

https://community.netlify.com/t/open-source-plan/5003/2
https://www.netlify.com/legal/open-source-policy/

**Comment by cbrzn** [comment]
#31
